version: 1.0.{build}

max_jobs: 1
image: Visual Studio 2019
configuration: Release

environment:
  matrix:
    - targetframework: net35
    - targetframework: net45
    - targetframework: net472
    - targetframework: net48
    - targetframework: netcoreapp3.0
    - targetframework: netcoreapp3.1

before_build:
- dotnet --version
- dotnet restore

for:
  -
    # dotnet test currently doesn't work for .NET Framework 3.5 - see comment in .travis.yml.
    matrix:
      only:
        - targetframework: net35
    test_script:
      - cmd: nunit3-console.exe HarmonyTests/bin/Release/%targetframework%/HarmonyTests.dll --inprocess --result=results.xml;format=AppVeyor
  -
    matrix:
      except:
        - targetframework: net35
    test_script:
    - cmd: cd HarmonyTests
    - cmd: nuget install Appveyor.TestLogger -Version 2.0.0
    - cmd: cd ..
    - cmd: dotnet test HarmonyTests --framework %targetframework% --test-adapter-path:. --logger:Appveyor

artifacts:
- path: 'Harmony\bin\Release\Lib.Harmony.*.nupkg'
